// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface Card {
    id: string;
    name: string;
    parameters: Apollo.CardParameter[];
    is_recommended: boolean;
}
