// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface ExternalTaskMessageOptionParameter {
    title: string;
    value?: ExternalTaskMessageOptionParameter.Value;
    type: Apollo.ParameterType;
}

export namespace ExternalTaskMessageOptionParameter {
    export type Value = string | (string | undefined)[] | number;
}
