// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface ExternalMessageCard {
    id: string;
    name: string;
    parameters: Apollo.ExternalMessageCardParameter[];
    is_recommended: boolean;
}
