// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface ExternalTaskMessage {
    id: string;
    created_at: string;
    text: string;
    sender: Apollo.ExternalTaskMessageContactParty;
    receiver: Apollo.ExternalTaskMessageContactParty;
    options: Apollo.ExternalTaskMessageOption[];
    variants_options: Apollo.ExternalTaskMessageOption[];
    followup_suggestions: string[];
}
