// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface ListExternalTasksResponse {
    tasks?: Apollo.CreateExternalTaskResponse[];
    total: number;
    page: number;
    size: number;
}
