// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface Message {
    id: string;
    created_at: string;
    text: string;
    sender: Apollo.MessageContactParty;
    receiver: Apollo.MessageContactParty;
    cards: Apollo.Card[];
    followup_suggestions: string[];
}
