// This file was auto-generated by Fern from our API Definition.

export const ApolloEnvironment = {
    Default: "https://azure.aui.io/api/ia-controller",
} as const;

export type ApolloEnvironment = typeof ApolloEnvironment.Default;
